sealed class Routes (val route: String) {
    object Home : Routes("Home")
    object Contacts : Routes("Contacts")
    object Favorites : Routes("Favorites")
    object Login : Routes("Login")
    object Register : Routes("Register")
    object Welcome : Routes("Welcome")
    object Main : Routes("Main")
    object Menu : Routes("Menu")
    object Documentation : Routes("Documentation")
    object CharacterDictionary : Routes("CharacterDictionary")
    object Map : Routes("Map")
    object Kupet : Routes("Kupet")
    object Friend : Routes("Friend")
    object FriendDetail : Routes("FriendDetail")
    object Quiz : Routes("Quiz")
    object CorrectAns : Routes("CorrectAns")
    object WrongAns : Routes("WrongAns")

    object Metro : Routes("Metro")
    object KonkukUnivStation : Routes("KonkukStation")
    object ChildrensGrandPark : Routes("ChildStation")
    object KueuiStation : Routes("KueuiStation")
}